eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:5555/eureka/
server:
  port: 4449
spring:
  application:
    name: provider2
# 数据库连接参数
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: root
    # 数据库连接池
    hikari:
      maximum-pool-size: 30     # 最大连接数
      minimum-idle: 10          # 最小连接数
      idle-timeout: 60000       # 超时时间

# 指定mapper文件路径 , 配置包中类别名
mybatis:
  mapper-locations: classpath*:com/zhang/mapper/*.xml
  type-aliases-package: com.zhang.entity

# 指定日志打印级别，输出SQL语句
logging:
  level:
    com.zhang.mapper: debug