eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:5555/eureka/
server:
 port: 8777
spring:
  application:
    name: service-provider
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0 # 设置数据库索引为0 默认为0
    password: # 密码为空
    jedis:
      pool:
        max-active: 1000 # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10 # 连接池中的最大空闲连接
        min-idle: 2 # 连接池中的最小空闲连接
    timeout: 2000 # 连接超时时间（毫秒）
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: root
    # 数据库连接池
    hikari:
      maximum-pool-size: 30     # 最大连接数
      minimum-idle: 10          # 最小连接数
      idle-timeout: 60000       # 超时时间

# 指定mapper文件路径 , 配置包中类别名
mybatis:
  mapper-locations: classpath*:zhang/mapper/*.xml
  type-aliases-package: zhang.entity
# 指定日志打印级别，输出SQL语句
logging:
  level:
    zhang.mapper: debug